#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor HDMI-0 -d I II III
bspc monitor DVI-I-1 -d IV V VI
bspc monitor DP-3 -d VII VIII IX X


bspc rule -a Gimp follow=on floating=on
bspc rule -a Chromium
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


panel &
